<a href="https://colab.research.google.com/github/Darshan0387/Assign-1/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
print(np.__version__)
print(np.show_config)

1.21.6
<function show at 0x7f9163aeea70>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [5]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [8]:
x = np.array([100,20,34])
print( x.size)
print( x.itemsize)

3
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [9]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [10]:
nullVector1_=np.zeros(10)
nullVector1_[4]=1
print(nullVector1_)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [11]:
arr= np.arange(10,49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [12]:
print(arr[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [13]:
q = np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8]
])
print(q)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [14]:
w=[1,2,0,0,4,0] 
print(*np.nonzero(w))

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [15]:
e = np.eye(3,3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [16]:
r = np.random.random((3,3,3))
print(r)

[[[0.85836233 0.08728503 0.62297607]
  [0.83521025 0.30883199 0.3677104 ]
  [0.66483965 0.24987285 0.97560728]]

 [[0.37052054 0.97991874 0.09952132]
  [0.14430224 0.3872879  0.54556947]
  [0.95779069 0.38642126 0.84412882]]

 [[0.37191818 0.64136012 0.81153633]
  [0.28684144 0.2142989  0.03245347]
  [0.57906154 0.17380469 0.10457016]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [17]:
t = np.random.random((10,10))
#print(arr10by10)
print("Max :", t.max())
print("Min :", t.min())

Max : 0.9904577361745281
Min : 0.0005642147478323034


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [18]:
y = np.random.random(30)
print("Mean :",y.mean())

Mean : 0.4749263309240526


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [20]:
u=np.ones((5,5))
u[1:-1, 1:-1]=0
print(u)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [21]:
zeroBorder = np.zeros((3,3))
print(np.pad(zeroBorder, (1, 1), 'constant', constant_values=(1, 2)))

[[1. 1. 1. 1. 2.]
 [1. 0. 0. 0. 2.]
 [1. 0. 0. 0. 2.]
 [1. 0. 0. 0. 2.]
 [1. 2. 2. 2. 2.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [22]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [25]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [26]:
arr8by8 = np.empty((8,8))
arr8by8[1::2,::2] = 1
#arr8by8[::2,::] = 1
print(arr8by8)

[[1.78026793e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [1.00000000e+000 0.00000000e+000 1.00000000e+000 0.00000000e+000
  1.00000000e+000 0.00000000e+000 1.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [1.00000000e+000 0.00000000e+000 1.00000000e+000 0.00000000e+000
  1.00000000e+000 0.00000000e+000 1.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [1.00000000e+000 0.00000000e+000 1.00000000e+000 0.00000000e+000
  1.00000000e+000 0.00000000e+000 1.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [1.00000000e+000 0.00000000e+000 1.00000000e+000 0.00000000e+000
  1

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [27]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [28]:
checkerboardArr=np.tile(np.array([[0,1],[1,0]]),(4,4)) 
print(checkerboardArr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [29]:
ranArr = np.random.random((5,5))
arrmax, arrmin = ranArr.max(), ranArr.min()
ranArr= (ranArr-arrmin)/(arrmax-arrmin)
print (ranArr)

[[0.67068349 0.61637396 0.28339656 0.13743287 0.92252916]
 [0.24076038 0.42883973 0.75107261 0.62539268 0.        ]
 [0.68560654 1.         0.69678253 0.0391287  0.83110866]
 [0.46783495 0.60381608 0.60176383 0.52562898 0.49108929]
 [0.03769376 0.39682131 0.76043442 0.22547413 0.71248657]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [31]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [32]:
arr5by3 = np.dot(np.random.random((5,3)), np.random.random((3,2)))
print (arr5by3)

[[0.67667688 1.37638165]
 [0.76456463 1.30322774]
 [0.40265702 0.39467464]
 [0.25084385 0.92574973]
 [0.57329992 0.73408132]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [33]:
arrZ = np.arange(11)
arrZ[(3 < arrZ) & (arrZ < 8)] *= -1
print(arrZ)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [34]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [35]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [36]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [37]:
aa=np.random.randint(0,15,(10))
bb =np.random.randint(0,15,(10))
#print(aa)
#print(aa)
print(np.intersect1d(aa, aa))


[ 2  3  6  7 13]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [38]:
np.seterr(over='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [40]:
#false

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [41]:
TodayDate=np.datetime64('today', 'D')
print("Yesterday : ", TodayDate-1)
print("Today : ", TodayDate)
print("Tomorrow : ", TodayDate+1)

Yesterday :  2022-11-08
Today :  2022-11-09
Tomorrow :  2022-11-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [42]:
print(np.arange(datetime64('2016-07-01'), datetime64('2016-07-31')))


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [43]:
np.multiply(np.add(A,B),np.divide(-A,2))

NameError: ignored

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [44]:
arr=np.random.random(3)*10
print(np.floor(arr))
print(np.trunc(arr))
print(np.ceil(arr))
print(arr.astype(int))

[9. 0. 9.]
[9. 0. 9.]
[10.  1. 10.]
[9 0 9]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [45]:
arr5by5 = np.zeros((5,5))
arr5by5 += np.arange(5)
arr5by5

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [46]:
def generator(): 
    for x in range(10):
        yield x
#print(*generator())
iterarr = np.fromiter(generator(), dtype=int, count=-1)
print (iterarr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [47]:
print(np.linspace(start=.1, stop=1, num=10, endpoint=False))

[0.1  0.19 0.28 0.37 0.46 0.55 0.64 0.73 0.82 0.91]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [48]:
arrsort = np.random.random(10)
arrsort.sort()
print(arrsort)

[0.11804629 0.29053736 0.34889986 0.35943929 0.41688505 0.45133883
 0.56030252 0.62291777 0.73374737 0.83511626]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [49]:
arr10 = np.arange(10)
np.add.reduce(arr10)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [50]:
Iarr = np.random.random(10)
IIarr = np.random.random(10)
np.allclose(Iarr, IIarr)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [51]:
i = np.zeros(10)
i.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [52]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X * 2 + Y * 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[1.60345216 1.20647496 1.06846175 0.90730993 1.93306466 1.37410684
 0.66551623 1.19642428 1.13392185 1.20904999]
[1.07515777 1.31073978 0.70997126 0.08102305 0.72455789 0.34723927
 0.12792222 1.01609082 0.40070888 1.23171086]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [53]:
arrof10 = np.random.random(10)
arrof10[arrof10.argmax()] = 0
print(arrof10)

[0.21682743 0.         0.52807126 0.63758032 0.71798042 0.77780942
 0.22468323 0.42216306 0.47824759 0.69615628]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [54]:
for dtype in [np.int8, np.int32, np.int64]:
   print(dtype," :",np.iinfo(dtype).min)
   print(dtype," :",np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
   print(dtype," :",np.finfo(dtype).min)
   print(dtype," :",np.finfo(dtype).max)
   print(dtype," :",np.finfo(dtype).eps)

<class 'numpy.int8'>  : -128
<class 'numpy.int8'>  : 127
<class 'numpy.int32'>  : -2147483648
<class 'numpy.int32'>  : 2147483647
<class 'numpy.int64'>  : -9223372036854775808
<class 'numpy.int64'>  : 9223372036854775807
<class 'numpy.float32'>  : -3.4028235e+38
<class 'numpy.float32'>  : 3.4028235e+38
<class 'numpy.float32'>  : 1.1920929e-07
<class 'numpy.float64'>  : -1.7976931348623157e+308
<class 'numpy.float64'>  : 1.7976931348623157e+308
<class 'numpy.float64'>  : 2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [55]:
arr10 = np.random.rand(3,3)
np.set_printoptions(precision=3)
print(arr10)

[[0.335 0.174 0.85 ]
 [0.331 0.714 0.774]
 [0.437 0.221 0.153]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [56]:
arrof10 = np.arange(10)
inval = int(input("input Scalar :"))
#print(arrof10)
index = (np.abs(arrof10-inval)).argmin()
print(arrof10[index])

input Scalar :5
5


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [57]:

rgbarr = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),
                        ('color',    [ ('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print(rgbarr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [58]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)*2 + (Y-Y.T)*2)
print(D)

[[0.      nan   nan   nan 0.874   nan   nan   nan   nan   nan]
 [0.409 0.      nan   nan 0.965   nan   nan 0.258   nan   nan]
 [0.574 0.403 0.      nan 1.046   nan 0.194 0.479   nan   nan]
 [0.903 0.805 0.697 0.    1.257 0.391 0.724 0.846   nan   nan]
 [  nan   nan   nan   nan 0.      nan   nan   nan   nan   nan]
 [0.815 0.704 0.577   nan 1.195 0.    0.609 0.75    nan   nan]
 [0.541 0.353   nan   nan 1.028   nan 0.    0.438   nan   nan]
 [0.317   nan   nan   nan 0.93    nan   nan 0.      nan   nan]
 [1.335 1.271 1.205 0.983 1.596 1.058 1.221 1.297 0.    0.861]
 [1.021 0.935 0.844 0.475 1.344 0.615 0.866 0.97    nan 0.   ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [59]:

fltarr = np.arange(10, dtype=np.float32)
intarr = fltarr.astype(np.int32, copy=False)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [61]:
enarr = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(enarr):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [62]:
arrX, arrY = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(arrX*arrX+arrY*arrY)
sigma, mu = 1.0, 0.0
Garr = np.exp(-( (D-mu)*2 / ( 2.0 * sigma*2 ) ) )
print(Garr)

[[0.493 0.531 0.564 0.59  0.605 0.605 0.59  0.564 0.531 0.493]
 [0.531 0.577 0.62  0.655 0.675 0.675 0.655 0.62  0.577 0.531]
 [0.564 0.62  0.675 0.723 0.753 0.753 0.723 0.675 0.62  0.564]
 [0.59  0.655 0.723 0.79  0.839 0.839 0.79  0.723 0.655 0.59 ]
 [0.605 0.675 0.753 0.839 0.924 0.924 0.839 0.753 0.675 0.605]
 [0.605 0.675 0.753 0.839 0.924 0.924 0.839 0.753 0.675 0.605]
 [0.59  0.655 0.723 0.79  0.839 0.839 0.79  0.723 0.655 0.59 ]
 [0.564 0.62  0.675 0.723 0.753 0.753 0.723 0.675 0.62  0.564]
 [0.531 0.577 0.62  0.655 0.675 0.675 0.655 0.62  0.577 0.531]
 [0.493 0.531 0.564 0.59  0.605 0.605 0.59  0.564 0.531 0.493]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [63]:
m = 5
p = 3
zeroarr = np.zeros((m,m))
np.put(zeroarr, np.random.choice(range(m), p,replace=False),1)
print (zeroarr)

[[1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [64]:
arri5 = np.random.rand(5, 10)
Yarr = arri5 - arri5.mean(axis=1, keepdims=True)
print(Yarr)

[[-0.129  0.182 -0.124 -0.276  0.02   0.089 -0.358  0.081  0.087  0.43 ]
 [-0.156 -0.092  0.434 -0.049 -0.273  0.059  0.154  0.358 -0.197 -0.238]
 [-0.255  0.006  0.382  0.49   0.003 -0.089 -0.209 -0.246 -0.318  0.238]
 [-0.442 -0.153 -0.101  0.25   0.486 -0.421  0.03   0.082 -0.132  0.401]
 [ 0.362  0.112  0.274 -0.113 -0.212 -0.368 -0.217  0.213 -0.406  0.354]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [65]:
ntharr = np.random.randint(0,10,(3,3))
print(ntharr[ntharr[:,1].argsort()])

[[7 2 0]
 [1 8 0]
 [3 9 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [66]:
nullarr = np.random.randint(0,3,(3,10))
print((~nullarr.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [67]:
arrof10 = np.random.random(10)
inval = float(input("input Scalar :"))
#print(arrof10)
index = (np.abs(arrof10-inval)).argmin()
print(arrof10[index])

input Scalar :13
0.9585606335028438


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [68]:
vct1=np.ones(10)
vct2 = np.random.randint(0,len(vct1),10)
np.add.at(vct1, vct2, 1)
print(vct1)

[2. 2. 1. 4. 1. 2. 3. 1. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [69]:
arrw = [1,2,3,4,5,6]
arry = [1,3,9,3,4,1]
binarr = np.bincount(arrw,arry)
print(binarr)

[0. 1. 3. 9. 3. 4. 1.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [70]:
arr4d = np.random.randint(0,10,(4,3,4))
#print(arr4d)
sumarr4d = arr4d.sum(axis=(-2,-1))
print(sumarr4d)

[61 59 67 61]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [71]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
Dsums = np.bincount(S, weights=D)
Dcounts = np.bincount(S)
Dmeans = Dsums / Dcounts
print(Dmeans)

[0.45  0.649 0.673 0.467 0.521 0.504 0.332 0.421 0.485 0.622]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [72]:
prodarr1 = np.random.randint(1,9,(3,3))
prodarr2 = np.random.randint(9,15,(3,3))
np.diag(np.dot(prodarr1, prodarr2))

array([256, 106, 189])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [73]:
arrA = np.ones((5,5,3))
arrB = np.ones((5,5))
print(arrA * arrB[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [74]:
swapA = np.arange(25).reshape(5,5)
swapA[[0,1]] = swapA[[1,0]]
print(swapA)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [75]:
binarr = np.bincount([1,1,2,3,4,4,6])
uniq = np.repeat(np.arange(len(binarr)), binarr)
print(uniq)

[1 1 2 3 4 4 6]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [76]:
negat = np.random.randint(0,2,100)
print(np.logical_not(negat, out=negat))


bolneg = np.random.uniform(-1.0,1.0,10)
print(np.negative(bolneg, out=bolneg))

[0 1 0 1 1 0 0 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 1 1 1 0 1 1 0 1 0 0 1
 1 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 0 1 0 1 0 0 0 1 1
 0 0 1 1 1 1 0 0 1 0 1 1 0 0 1 0 1 0 1 1 0 0 0 0 1 1]
[ 0.935 -0.449  0.584  0.737  0.285 -0.27  -0.607  0.829 -0.677  0.31 ]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [77]:
arr3by3 = np.arange(10)
rank = np.linalg.matrix_rank(arr3by3)
print(rank)

1


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [78]:

arr3by3 = np.random.randint(0,10,5)
print(np.bincount(arr3by3).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [79]:
arrXL = np.random.randint(0,10,50000)
n=int(input("Type n ="))
print (arrXL[np.argsort(arrXL)[-n:]])

Type n =5
[9 9 9 9 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)